version: '3'
services:
  webscraper:
    build: .
    container_name: webscraper
    command: ["sh", "-c", "sleep 30 && python icons_scraper.py"]
    depends_on:
      - selenium-hub
      - chrome
    volumes:
      - ./output:/app/output
  chrome:
    image: selenium/node-chrome:4.22.0-20240621
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    image: selenium/hub:4.22.0-20240621
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
